apiVersion: v1
kind: Service
metadata:
  name: playground-detector-svc
spec:
  type: NodePort # 使用节点端口模式，方便本地访问
  selector:
    app: playground-detector # 指向刚才定义的 Deployment
  ports:
    - protocol: TCP
      port: 80 # Service 暴露的端口
      targetPort: 8080 # 容器内部的端口
      nodePort: 30008 # 固定一个外部访问端口 (30000-32767之间)